import type { Theme } from '../types/os';

export const themes: Theme[] = [
  {
    id: 'win95',
    name: 'Windows 95',
    colors: {
      desktopBg: '#008080',
      taskbarBg: '#c0c0c0',
      taskbarText: '#000000',
      taskbarHighlight: '#ffffff',
      taskbarShadow: '#808080',
      windowBg: '#c0c0c0',
      windowBorder: '#000000',
      windowTitleBarActiveStart: '#000080',
      windowTitleBarActiveEnd: '#1084d0',
      windowTitleBarInactiveStart: '#808080',
      windowTitleBarInactiveEnd: '#a0a0a0',
      windowTitleTextActive: '#ffffff',
      windowTitleTextInactive: '#c0c0c0',
      buttonFace: '#c0c0c0',
      buttonHighlight: '#ffffff',
      buttonShadow: '#808080',
      buttonText: '#000000',
      selectedBg: '#000080',
      selectedText: '#ffffff',
      menuBg: '#c0c0c0',
      menuText: '#000000',
      menuHighlight: '#000080',
      accent: '#000080',
    },
  },
  {
    id: 'win98',
    name: 'Windows 98',
    colors: {
      desktopBg: '#3a6ea5',
      taskbarBg: '#c0c0c0',
      taskbarText: '#000000',
      taskbarHighlight: '#ffffff',
      taskbarShadow: '#808080',
      windowBg: '#c0c0c0',
      windowBorder: '#000000',
      windowTitleBarActiveStart: '#0055ee',
      windowTitleBarActiveEnd: '#3590f3',
      windowTitleBarInactiveStart: '#808080',
      windowTitleBarInactiveEnd: '#a0a0a0',
      windowTitleTextActive: '#ffffff',
      windowTitleTextInactive: '#c0c0c0',
      buttonFace: '#c0c0c0',
      buttonHighlight: '#ffffff',
      buttonShadow: '#808080',
      buttonText: '#000000',
      selectedBg: '#000080',
      selectedText: '#ffffff',
      menuBg: '#c0c0c0',
      menuText: '#000000',
      menuHighlight: '#000080',
      accent: '#0055ee',
    },
  },
  {
    id: 'win2000',
    name: 'Windows 2000',
    colors: {
      desktopBg: '#3a6ea5',
      taskbarBg: '#d4d0c8',
      taskbarText: '#000000',
      taskbarHighlight: '#ffffff',
      taskbarShadow: '#808080',
      windowBg: '#d4d0c8',
      windowBorder: '#000000',
      windowTitleBarActiveStart: '#0a246a',
      windowTitleBarActiveEnd: '#a6caf0',
      windowTitleBarInactiveStart: '#808080',
      windowTitleBarInactiveEnd: '#bfbfbf',
      windowTitleTextActive: '#ffffff',
      windowTitleTextInactive: '#e0e0e0',
      buttonFace: '#d4d0c8',
      buttonHighlight: '#ffffff',
      buttonShadow: '#808080',
      buttonText: '#000000',
      selectedBg: '#316ac5',
      selectedText: '#ffffff',
      menuBg: '#d4d0c8',
      menuText: '#000000',
      menuHighlight: '#316ac5',
      accent: '#316ac5',
    },
  },
  {
    id: 'winxp',
    name: 'Windows XP',
    colors: {
      desktopBg: '#3a6ea5',
      taskbarBg: '#ece9d8',
      taskbarText: '#000000',
      taskbarHighlight: '#ffffff',
      taskbarShadow: '#aca899',
      windowBg: '#ece9d8',
      windowBorder: '#0a246a',
      windowTitleBarActiveStart: '#0a64d8',
      windowTitleBarActiveEnd: '#4291ff',
      windowTitleBarInactiveStart: '#8c9bb8',
      windowTitleBarInactiveEnd: '#b3c6e0',
      windowTitleTextActive: '#ffffff',
      windowTitleTextInactive: '#e0e0e0',
      buttonFace: '#ece9d8',
      buttonHighlight: '#ffffff',
      buttonShadow: '#aca899',
      buttonText: '#000000',
      selectedBg: '#316ac5',
      selectedText: '#ffffff',
      menuBg: '#ffffff',
      menuText: '#000000',
      menuHighlight: '#316ac5',
      accent: '#316ac5',
    },
  },
  {
    id: 'macos9',
    name: 'Classic Mac',
    colors: {
      desktopBg: '#d4d0c8',
      taskbarBg: '#d4d0c8',
      taskbarText: '#000000',
      taskbarHighlight: '#ffffff',
      taskbarShadow: '#808080',
      windowBg: '#ffffff',
      windowBorder: '#000000',
      windowTitleBarActiveStart: '#000000',
      windowTitleBarActiveEnd: '#404040',
      windowTitleBarInactiveStart: '#808080',
      windowTitleBarInactiveEnd: '#a0a0a0',
      windowTitleTextActive: '#ffffff',
      windowTitleTextInactive: '#e0e0e0',
      buttonFace: '#d4d0c8',
      buttonHighlight: '#ffffff',
      buttonShadow: '#808080',
      buttonText: '#000000',
      selectedBg: '#000000',
      selectedText: '#ffffff',
      menuBg: '#ffffff',
      menuText: '#000000',
      menuHighlight: '#000000',
      accent: '#000000',
    },
  },
  {
    id: 'highcontrast',
    name: '高对比度',
    colors: {
      desktopBg: '#000000',
      taskbarBg: '#000000',
      taskbarText: '#ffffff',
      taskbarHighlight: '#00ffff',
      taskbarShadow: '#808080',
      windowBg: '#000000',
      windowBorder: '#ffffff',
      windowTitleBarActiveStart: '#000000',
      windowTitleBarActiveEnd: '#000000',
      windowTitleBarInactiveStart: '#404040',
      windowTitleBarInactiveEnd: '#404040',
      windowTitleTextActive: '#00ffff',
      windowTitleTextInactive: '#808080',
      buttonFace: '#000000',
      buttonHighlight: '#ffffff',
      buttonShadow: '#808080',
      buttonText: '#ffffff',
      selectedBg: '#00ffff',
      selectedText: '#000000',
      menuBg: '#000000',
      menuText: '#ffffff',
      menuHighlight: '#00ffff',
      accent: '#00ffff',
    },
  },
];

export const defaultThemeId = 'win95';

export function getThemeById(id: string): Theme {
  return themes.find((t) => t.id === id) || themes[0];
}

export function applyTheme(theme: Theme): void {
  const root = document.documentElement;
  Object.entries(theme.colors).forEach(([key, value]) => {
    root.style.setProperty(`--os-${key}`, value);
  });
}
